# Generated by Django 4.2.2 on 2023-06-28 18:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='level')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='discount')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('expired_date', models.IntegerField(default=12, verbose_name='expired_date')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=16, verbose_name='last_name')),
                ('dob', models.DateField(verbose_name='dob')),
                ('phone', models.CharField(max_length=16, verbose_name='phone')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('wechat', models.CharField(blank=True, max_length=50, null=True, verbose_name='wechat')),
                ('address', models.DateField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('register_date', models.DateField(default=datetime.datetime(2023, 6, 28, 18, 13, 24, 545438, tzinfo=datetime.timezone.utc), verbose_name='register_date')),
                ('deleted', models.BooleanField(default=0, verbose_name='deleted')),
                ('membership_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend.membership', verbose_name='membership_id')),
            ],
        ),
    ]
