# Generated by Django 4.2.2 on 2023-06-28 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(db_index=True, max_length=16, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(db_index=True, max_length=16, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 18, 15, 22, 630551, tzinfo=datetime.timezone.utc), verbose_name='register_date'),
        ),
    ]
