# Generated by Django 4.2.2 on 2023-06-28 19:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_userinfo_email_alter_userinfo_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(db_index=True, max_length=16, verbose_name='item_name')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='item_price')),
                ('item_detail', models.TextField(verbose_name='item_detail')),
                ('item_frequency', models.IntegerField(default=1, verbose_name='item_frequency')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='credit'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 19, 5, 18, 597532, tzinfo=datetime.timezone.utc), verbose_name='register_date'),
        ),
        migrations.CreateModel(
            name='serviceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime(2023, 6, 28, 19, 5, 18, 610245, tzinfo=datetime.timezone.utc), verbose_name='start_date')),
                ('client_info', models.TextField(verbose_name='client_info')),
                ('consumeItem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.consumeitem', verbose_name='consumeItem_id')),
                ('userInfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userinfo', verbose_name='userInfo_id')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.IntegerField(verbose_name='payment_amount')),
                ('payment_date', models.DateField(default=datetime.datetime(2023, 6, 28, 19, 5, 18, 609781, tzinfo=datetime.timezone.utc), verbose_name='payment_date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('userInfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userinfo', verbose_name='userInfo_id')),
            ],
        ),
        migrations.CreateModel(
            name='MemberConsume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_amount', models.IntegerField(verbose_name='consume_amount')),
                ('consume_date', models.DateField(default=datetime.datetime(2023, 6, 28, 19, 5, 18, 609947, tzinfo=datetime.timezone.utc), verbose_name='consume_date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('deleted', models.BooleanField(default=0, verbose_name='deleted')),
                ('consumeItem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.consumeitem', verbose_name='consumeItem_id')),
                ('userInfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userinfo', verbose_name='userInfo_id')),
            ],
        ),
    ]
