# Generated by Django 4.2.2 on 2023-06-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_memberconsume_consume_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberconsume',
            name='consume_date',
            field=models.DateField(verbose_name='consume_date'),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='payment_date',
            field=models.DateField(verbose_name='payment_date'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='start_date',
            field=models.DateField(verbose_name='start_date'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='register_date',
            field=models.DateField(verbose_name='register_date'),
        ),
    ]
