# Generated by Django 4.2.2 on 2023-06-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_userinfo_password_alter_userinfo_membership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='phone'),
        ),
    ]
